server:
  port: 8082
spring:
  application:
    name: ftgo-order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ftgo_order
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJFdmVyeW9uZSIsIlVzZXJuYW1lIjoiRXZlcmJvZHkifQ
ftgo:
  service:
    kitchen-url: http://localhost:8083
    accounting-url: http://localhost:8084


resilience4j:
  circuitbreaker:
    instances:
      kitchenService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      accountingService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  timelimiter:
    instances:
      kitchenService:
        timeoutDuration: 2s
      accountingService:
        timeoutDuration: 2s
  retry:
    instances:
      kitchenService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      accountingService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

logging:
  level:
    org.springframework.security: DEBUG
    com.ftgo: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.openfeign: DEBUG