server:
  port: 8080
spring:
  application:
    name: ftgo-api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/orders

        - id: kitchen-service
          uri: http://localhost:8083
          predicates:
            - Path=/kitchen/**
          filters:
            - name: CircuitBreaker
              args:
                name: kitchenCircuitBreaker
                fallbackUri: forward:/fallback/kitchen

        - id: accounting-service
          uri: http://localhost:8084
          predicates:
            - Path=/accounting/**
          filters:
            - name: CircuitBreaker
              args:
                name: accountingCircuitBreaker
                fallbackUri: forward:/fallback/accounting

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJFdmVyeW9uZSIsIlVzZXJuYW1lIjoiRXZlcmJvZHkifQ
